# TODO:フロントビルド
# TODO:バックエンドビルド
# TODO:テスト
#
version: 0.1

environment_variables:
  plaintext:
    MY_ENV: "damagecalculator"

phases:
  build:
    commands:
      - echo build started on `date`
      - go build application.go
    finally:
      - echo build completed
  artifacts:
    type: zip
    file:
      - damagecalculator
