# TODO:フロントビルド
# TODO:バックエンドビルド
# TODO:テスト
#
version: 0.2

phases:
  install:
#    runtime-versions:
#      golang: 1.12
    commands:
      - echo Nothing to do in the install phase...
    finally:
      - echo install completed.
  pre_build:
    commands:
      - echo nothing to do in the prebuild phase...
    finally:
      - echo prebuild completed.
  build:
    commands:
      - echo build started.
      - go build application.go
#      - go test ./...
    finally:
      - echo build completed
  post_build:
    commands:
      - echo build completed.
    finally:
      - echo postbuild completed
  artifacts:
    files:
      - damagecalculator/damagecalculator

