# TODO:フロントビルド
# TODO:バックエンドビルド
# TODO:テスト
#
version: 0.2

phases:
  install:
#    runtime-versions:
#      golang: 1.12
    commands:
      - cd ./frontend
      - ls
      - echo update npm...
      - npm install -g n
      - n latest
      - npm update -g npm
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - cd ../
    finally:
      - echo install completed.
  pre_build:
    commands:
      - echo installing source NPM dependencies...
      - cd ./frontend
      - npm install
      - cd ../
    finally:
      - echo prebuild completed.
  build:
    commands:
      - echo build frontend.
      - cd ./frontend
      - npm run build
      - cd ../
      - echo build backend.
      - go build application.go
    finally:
      - echo build completed
      - ls
  post_build:
    commands:
      - echo build completed.

# artifacts: 先頭にインデント入れるだけで失敗する(phaseに認識されている)
# 作成できたファイルをS3にアップロードする
artifacts:
  files:
    - application
  discard-paths: yes
#cache:
#  paths:
#    - '/root/.m2/**/*'
