version: 0.2

phases:
  install:
#    runtime-versions:
#      golang: 1.12
    commands:
      - cd ./frontend
      - ls
      - echo update npm...
      - npm install -g n
      - n latest
      - npm i update -g npm to update
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - cd ../
    finally:
      - echo install completed.
  pre_build:
    commands:
      - echo installing source NPM dependencies...
      - cd ./frontend
      - rm -rf node_modules package-lock.json && npm install
      - cd ../
    finally:
      - echo prebuild completed.
  build:
    commands:
      - echo build frontend.
      - cd ./frontend
      - npm run build
      - cd ../
      - echo build backend.
      - go build application.go
    finally:
      - echo build completed
      - ls
  post_build:
    commands:
      - echo build completed.
      - zip -r application.zip *
#      - go test ./...

artifacts:
  files:
    - 'application.zip'
#    - 'application'
#    - './frontend/dist/**/*'
  discard-paths: no
